FROM us-docker.pkg.dev/qwiklabs-resources/healthcare-qwiklabs-resources/dataflow-pipeline:v0.02

COPY ./converter-hdc.jar /root/converter-hdc.jar
COPY ./entrypoint2.sh /root/entrypoint2.sh

RUN chmod +x /root/entrypoint2.sh
